### ISSUE TITLE
(Bug) "npm run start-test-setup" doesn't work

### ISSUE THREAD

**Issue by volkrass** [poanetwork/poa-test-setup#1]
bash: ./make_flat.sh: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! poa-test-setup@0.1.0 prepare-contracts-repo: `bash ./scripts/prepare-contracts-repo`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the poa-test-setup@0.1.0 prepare-contracts-repo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vhahn/.npm/_logs/2018-02-19T22_59_21_588Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poa-test-setup@0.1.0 start-test-setup: `npm run get-all-submodules && npm run prepare-contracts-repo && npm run prepare-moc-node && npm run start-moc-node && npm run deploy-secondary-contracts && npm run prepare-scrips-moc-repo && npm run prepare-ceremony-dapp && npm run prepare-ceremony-dapp-more && npm run generate-initial-keys && npm run get-private-initial-keys && npm run start-ceremony && npm run test-setup-is-started`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poa-test-setup@0.1.0 start-test-setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in: ...

Log file entries:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.3.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start-test-setup' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose run-script [ 'prestart-test-setup',
4 verbose run-script   'start-test-setup',
4 verbose run-script   'poststart-test-setup' ]
5 info lifecycle poa-test-setup@0.1.0~prestart-test-setup: poa-test-setup@0.1.0
6 info lifecycle poa-test-setup@0.1.0~start-test-setup: poa-test-setup@0.1.0
7 verbose lifecycle poa-test-setup@0.1.0~start-test-setup: unsafe-perm in lifecycle true
8 verbose lifecycle poa-test-setup@0.1.0~start-test-setup: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/vhahn/Projects/blockchain/poa.network/poa-test-setup/node_modules/.bin:/Users/vhahn/.cargo/bin:/Users/vhahn/Projects/experiments/flutter/bin:/Users/vhahn/.dnx/runtimes/dnx-mono.1.0.0-rc1-final/bin:/Users/vhahn/.rbenv/shims:/Users/vhahn/.rbenv/bin:/usr/local/sbin:/usr/local/cmake/bin:/Users/vhahn/bin:/Library/Frameworks/Mapnik.framework/Programs:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/deployd/bin:/Users/vhahn/.rvm/bin:/Users/vhahn/Library/Android/sdk/tools:/Library/Frameworks/JRuby.framework/Versions/Current/bin:/Users/vhahn/Projects/ant/bin:/Users/vhahn/Library/Android/sdk/platform-tools:~/.pub-cache/bin:/Users/vhahn/go/bin:/usr/local/opt/go/libexec/bin
9 verbose lifecycle poa-test-setup@0.1.0~start-test-setup: CWD: /Users/vhahn/Projects/blockchain/poa.network/poa-test-setup
10 silly lifecycle poa-test-setup@0.1.0~start-test-setup: Args: [ '-c',
10 silly lifecycle   'npm run get-all-submodules && npm run prepare-contracts-repo && npm run prepare-moc-node && npm run start-moc-node && npm run deploy-secondary-contracts && npm run prepare-scrips-moc-repo && npm run prepare-ceremony-dapp && npm run prepare-ceremony-dapp-more && npm run generate-initial-keys && npm run get-private-initial-keys && npm run start-ceremony && npm run test-setup-is-started' ]
11 silly lifecycle poa-test-setup@0.1.0~start-test-setup: Returned: code: 1  signal: null
12 info lifecycle poa-test-setup@0.1.0~start-test-setup: Failed to exec start-test-setup script
13 verbose stack Error: poa-test-setup@0.1.0 start-test-setup: `npm run get-all-submodules && npm run prepare-contracts-repo && npm run prepare-moc-node && npm run start-moc-node && npm run deploy-secondary-contracts && npm run prepare-scrips-moc-repo && npm run prepare-ceremony-dapp && npm run prepare-ceremony-dapp-more && npm run generate-initial-keys && npm run get-private-initial-keys && npm run start-ceremony && npm run test-setup-is-started`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid poa-test-setup@0.1.0
15 verbose cwd /Users/vhahn/Projects/blockchain/poa.network/poa-test-setup
16 verbose Darwin 17.5.0
17 verbose argv "/usr/local/Cellar/node/9.3.0_1/bin/node" "/usr/local/bin/npm" "run" "start-test-setup"
18 verbose node v9.3.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error poa-test-setup@0.1.0 start-test-setup: `npm run get-all-submodules && npm run prepare-contracts-repo && npm run prepare-moc-node && npm run start-moc-node && npm run deploy-secondary-contracts && npm run prepare-scrips-moc-repo && npm run prepare-ceremony-dapp && npm run prepare-ceremony-dapp-more && npm run generate-initial-keys && npm run get-private-initial-keys && npm run start-ceremony && npm run test-setup-is-started`
22 error Exit status 1
23 error Failed at the poa-test-setup@0.1.0 start-test-setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Hope it helps

**Comment by vbaranov** [comment]
I extended requirements for executing https://github.com/poanetwork/poa-test-setup#requirements and I updated bash scripts to handle errors.

Could you pull the update from the repo, check requirements and let me know, if it works for you now?
If it still won't work, please provide new logs and also:
- what is your OS?
- did you install packages with `npm i` before executing script?

**Comment by mwaysolutions** [comment]
Pulled the new version, now it proceed further,
but struggle on script "node prepareMoCScripts.js"

Using Mac OS High Sierra
I have installed everything with npm i

**Comment by volkrass** [comment]
Latest version solved the issues. Keep up the good work.

**Comment by volkrass** [comment]
I pulled newest version of your repo and now the bug is back. 
The script struggles here, again:

> bash ./scripts/deploy-secondary-contracts

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poa-test-setup@0.1.0 deploy-secondary-contracts: `bash ./scripts/deploy-secondary-contracts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poa-test-setup@0.1.0 deploy-secondary-contracts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2018-03-01T16_07_41_320Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poa-test-setup@0.1.0 start-test-setup: `npm run get-all-submodules && npm run prepare-contracts-repo && npm run prepare-moc-node && npm run start-moc-node && npm run deploy-secondary-contracts && npm run prepare-scrips-moc-repo && npm run prepare-ceremony-dapp && npm run prepare-ceremony-dapp-more && npm run generate-initial-keys && npm run get-private-initial-keys && npm run start-ceremony && npm run test-setup-is-started`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poa-test-setup@0.1.0 start-test-setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2018-03-01T16_07_41_351Z-debug.log

 Any advice would be appreciated.

**Comment by vbaranov** [comment]
@volkrass 

Could you take a look at the list of deployment scenarios https://github.com/poanetwork/poa-test-setup#basic-scenarios ? please let me know if it works for you.

`npm run start-test-setup` is not supported anymore.

**Comment by mwaysolutions** [comment]
I can confirm, it is fixed. Thanks for your support.

**Comment by volkrass** [comment]
Thanks again for your support. I can confirm, it is fixed.
