### ISSUE TITLE
(Fix) Remove poa-chain-spec submodule from poa-test-setup

### ISSUE THREAD

**Issue by varasev** [poanetwork/poa-test-setup#19]
@rstormsf @vbaranov 

It seems that `poa-chain-spec` submodule is not used anywhere in `poa-test-setup`.

Can we safely remove this submodule from `poa-test-setup`?

**Comment by vbaranov** [comment]
@varasev yes, submodule is not used anymore. We can safely delete it. We get spec and ABI of contracts from github on fly.
