### ISSUE TITLE
Starting more validators #open

### ISSUE THREAD

**Issue by medve-dev** [poanetwork/poa-test-setup#54]
link issues https://github.com/poanetwork/poa-test-setup/issues/50#issue-365183752
if I disable the validator_1 network stops working and find blocks

all validators are only seen as peers
![image](https://user-images.githubusercontent.com/31813944/46252331-3b980580-c470-11e8-830d-e33bb455abb9.png)

how to add a few?

npm run launch-ceremony
image
![image](https://user-images.githubusercontent.com/31813944/46252297-c62c3500-c46f-11e8-8367-5c08db9eafbc.png)

ERROR!

**Comment by vbaranov** [comment]
@medve-dev does it work for you finally?

**Comment by medve-dev** [comment]
yes  it work  thank  you very much
