### ISSUE TITLE
What are the steps to bootstrap a basic private blockchain?

### ISSUE THREAD

**Issue by aknuds1** [poanetwork/poa-test-setup#60]
This repository is the best resource I've found so far on understanding how to get started with POA Network, especially as someone new to Ethereum/blockchain, but I'm still not sure after reviewing the options and the available NPM scripts.

So far, my experience with creating a local Ethereum network is limited to the [demo PoA tutorial](https://wiki.parity.io/Demo-PoA-tutorial) from Parity. How can I set up an equivalent basic network with POA Network? Is there one of the NPM scripts in package.json I can use?

Appreciate any help!

**Comment by varasev** [comment]
We have detailed information about how to setup Master of Ceremony node and Validators' nodes in our Wiki: https://github.com/poanetwork/wiki/wiki (see `Roles` section).

The `poa-test-setup` repeats all the steps necessary for launching local private demo network consist of three validators (Master of Ceremony and two validators).

Also, there are a few short steps available in https://github.com/poanetwork/poa-network-consensus-contracts/blob/master/scripts/README.md which can help on nodes launching.

To figure out how the nodes can be configured and started, you can take a look at the simple setup available in https://github.com/varasev/test-block-reward (without full consensus contracts) - just to understand how the Parity can be started in AuRa mode.

**Comment by aknuds1** [comment]
Thanks @varasev - in the meantime I was also shown the Ansible/Terraform setup for deploying POA Network to Azure. I've read through it now and find it highly informational. I've already started adapting it for Google Cloud.
