### ISSUE TITLE
start-moc-node and start-validator-node don't install Parity

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/poa-test-setup#66]
This might arguably be a non-issue since the README states the Parity 1.9.2 requirement. However those two scripts make an undocumented attempt to install Parity from a deb package and don't fetch that package themselves. That attempt doesn't work unless there is a deb package already in place. I wonder whether these scripts need to make such an attempt at all. Possibly it's better to report an error when Parity is not available or has an unsupported version.

**Comment by vbaranov** [comment]
Indeed, trying to install from deb package is not documented and it seems not so helpful for devs because deb package should be downloaded manually. I will remove that part. And thank you for the suggestion to check the client version. Will add it.
